version: build.{build}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi-CosmosDb.ps1 $nuget_version
test_script:
- cmd: nunit-console-x86 NBi.Testing\bin\debug\NBi.Testing.CosmosDb.dll /exclude:Acceptance,Olap,Etl,WindowsService,ReportServerDB,LocalSQL
artifacts:
- path: NBi.Core.CosmosDb\bin\Debug
  name: NBi.CosmosDb
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/nbi-cosmodb/api/v2/package
  api_key:
    secure: +E89GuWTCkM1DpiRGoO3oRLIvLIjb8aPsHqNvga0ID/xdUx0cvDjI7XVdF12rmEm
  on:
    branch: develop